### ISSUE TITLE
The "About' is already implemented internally.

### ISSUE THREAD

**Issue by Keithno** [Tacodude7729/Open-Scratch#2]
Scratch projects by default are already open sourced. The creator will hopefully credit others if they used there work and furthermore the viewer is able to see all spites, blocks, and other contents inside the project. Therefore, I strongly advise you update the "About" to something clearer.

Warm wishes,
Lumins [@Keithno]

**Comment by Tacodude7729** [comment]
To me, open-source means people can contribute through pull requests. I would argue that scratch projects are not open source, they are source-available. Perhaps you're right though - its real purpose is to allow scratch projects to use git. I'll change the readme when I do the next commit.
