### ISSUE TITLE
"No verb selected" error when running the executable on macOS

### ISSUE THREAD

**Issue by BackThePortal** [Tacodude7729/Open-Scratch#3]
When I run the Unix executable, I just see this:

<img width="475" alt="Captura de Pantalla 2021-12-29 a les 22 18 43" src="https://user-images.githubusercontent.com/77280741/147704131-3b4ce9ed-71ac-475a-bad2-6d24e183da7f.png">

At the end says "Process completed".

How do I fix this?

**Comment by Tacodude7729** [comment]
Are you providing it with arguments? It's a command line program so you need to tell it what you want it to do via the command line. See the README of this repo for some example usages.

**Comment by BackThePortal** [comment]
I've read the README. I've tried to open the terminal and write a command like the one in the README, but it won't recognize "openscratch".

**Comment by BackThePortal** [comment]
Maybe I wasn't clear: the screenshot shows what I see when I run the executable. I didn't type anything. I just run the executable and it doesn't let me type anything after I see the "process completed" message.

**Comment by Tacodude7729** [comment]
You need to run the executable from the command line. I'm not sure how you do this on OSX, but I'm assuming you need to use the cd command to move to the directory containing the executable and run './openscratch assemble' or whatever the executable is called. I'm not at my computer right now so I can't help you to much more than that right now... sorry.

**Comment by BackThePortal** [comment]
Okay! Now it worked! I had to create the "sprites" folder, though. If I don't create that folder, I get this error:
```
Unexpected error while parsing SB3 <file name>. System.IO.DirectoryNotFoundException: Could not find a part of the path '<path>/sprites'.
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at OpenScratch.CommandLine.Disassemble(DisassembleOptions options)
```
Maybe the executable should create the folder "sprites" first?
I'm happy it worked though, thank you!

**Comment by BackThePortal** [comment]
Also, it would be cool if these two things (opening the executable from the command line and creating the folder "assets") were in the README. That would help other people who aren't command line experts :trollface:

**Comment by Tacodude7729** [comment]
You shouldn't have to create the folders yourself. I was working on an update to this which makes a lot of things better and makes it much more usable. tbh I wasn't really indending for other people to use this yet, it was just a personal thing for my project I thought I'd share. Some of these UX things should be addressed when I eventually have time to update
